extern const GeoLayout bowser_1_area_1_geo[];
extern const GeoLayout bowser_1_area_1[];
extern const Collision bowser_1_area_1_collision[];
extern const MacroObject bowser_1_area_1_macro_objs[];
extern u8 bowser_1_dl_Pattern_01_Retro_Wallpaper_Orange_1_64x64_i4[];
extern u8 bowser_1_dl_very_weird_grass_i8[];
extern u8 bowser_1_dl_x_wall_I_love_so_much_i8[];
extern u8 bowser_1_dl_Art279_64x64_i4[];
extern u8 bowser_1_dl_greyface_alt_64x64__CRUELTY_SQUAD__i4[];
extern u8 bowser_1_dl_up_tile_yellow_i8[];
extern u8 bowser_1_dl__05006078_ci8[];
extern u8 bowser_1_dl__05006078_pal_rgba16[];
extern u8 bowser_1_dl_Stone_01_64x64_i4[];
extern u8 bowser_1_dl_striped_peach_bricks_rgba16[];
extern Vtx bowser_1_dl_Circle_mesh_layer_1_vtx_cull[8];
extern Vtx bowser_1_dl_Circle_mesh_layer_1_vtx_0[40];
extern Gfx bowser_1_dl_Circle_mesh_layer_1_tri_0[];
extern Vtx bowser_1_dl_Circle_mesh_layer_1_vtx_1[50];
extern Gfx bowser_1_dl_Circle_mesh_layer_1_tri_1[];
extern Vtx bowser_1_dl_Circle_mesh_layer_1_vtx_2[40];
extern Gfx bowser_1_dl_Circle_mesh_layer_1_tri_2[];
extern Vtx bowser_1_dl_Circle_mesh_layer_1_vtx_3[12];
extern Gfx bowser_1_dl_Circle_mesh_layer_1_tri_3[];
extern Vtx bowser_1_dl_Circle_mesh_layer_1_vtx_4[71];
extern Gfx bowser_1_dl_Circle_mesh_layer_1_tri_4[];
extern Gfx mat_bowser_1_dl_floor_layer1[];
extern Gfx mat_revert_bowser_1_dl_floor_layer1[];
extern Gfx mat_bowser_1_dl_star_layer1[];
extern Gfx mat_revert_bowser_1_dl_star_layer1[];
extern Gfx mat_bowser_1_dl_face_wall_layer1[];
extern Gfx mat_revert_bowser_1_dl_face_wall_layer1[];
extern Gfx mat_bowser_1_dl_env_map[];
extern Gfx mat_revert_bowser_1_dl_env_map[];
extern Gfx mat_bowser_1_dl_stone_layer1[];
extern Gfx mat_revert_bowser_1_dl_stone_layer1[];
extern Gfx bowser_1_dl_Circle_mesh_layer_1[];
